### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by cristianmadularu** [libp2p/js-libp2p-prometheus-metrics#33]
Hi, 

Is there any way of running this lib in a browser? I see that it requires node for some of the metrics it captures (ex. memory usage), but is there a way to indicate that those should be skipped and to only extract the lib2p2 metrics?

Thanks!

**Comment by maschad** [comment]
The underlying library which this extends  i.e. [prom-client](https://github.com/siimon/prom-client) utilizes node's [worker threads](https://nodejs.org/api/worker_threads.html) and aggregates them from the global registry, so this library is merely an extension of that with some exposed methods to make it easier to collect libp2p specific metrics as well. 

There are a few alternatives for your use case:

- as mentioned [here](https://discuss.libp2p.io/t/lip2p-metrics-browser/1976/4) you could explore leveraging [GitHub - weaveworks/promjs](https://github.com/weaveworks/promjs) along with our [Events API](https://libp2p.github.io/js-libp2p-interfaces/interfaces/_libp2p_interface_libp2p.Libp2pEvents.html) to capture some of these metrics.
- Using [Push Metrics](https://prometheus.io/docs/instrumenting/pushing/) , the [Prometheus Pushgateway](https://github.com/prometheus/pushgateway) allows you to push time series from [short-lived service-level batch jobs](https://prometheus.io/docs/practices/pushing/) to an intermediary job which Prometheus can scrape.

But I don't think extending this library would be the easiest way to achieve your goal.
